const mongoose = require('mongoose')

const visitSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: 'User',
  },
  visited: {
    type: Boolean,
    default: true,
  },
  name: Object,
  tld: [String],
  cca2: String,
  ccn3: String,
  cca3: String,
  cioc: String,
  independent: Boolean,
  status: String,
  unMember: Boolean,
  currencies: Object,
  idd: Object,
  capital: [String],
  altSpellings: [String],
  region: String,
  subregion: String,
  languages: Object,
  translations: Object,
  latlng: [],
  landlocked: Boolean,
  borders: [String],
  area: Number,
  demonyms: Object,
  flag: String,
  maps: Object,
  population: Number,
  gini: Object,
  fifa: String,
  car: Object,
  timezones: [String],
  continents: [String],
  flags: Object,
  coatOfArms: Object,
  startOfWeek: String,
  capitalInfo: Object,
  postalCode: Object,
})

module.exports = mongoose.model('Visit', visitSchema)
