name: Production workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
      # Utilize a cache when installing deps for a potentially quicker build
      - uses: bahmutov/npm-install@v1
      - run: cd client && yarn test
      - name: Checkout code
      - name: Use Node.js 17.x
      - run: npm install
      - run: npm run build --if-present
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "bag-2022"
          heroku_email: "ashakur24@hotmail.com"
