name: Test

on: [push, pull_request]

defaults:
  run:
    working-directory: client

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn test
